// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4tW8ZPBMcjs6yrjV2lOSicmzht1zRUgw',
    appId: '1:196726945085:android:a6a469fe5c43182cb60154',
    messagingSenderId: '196726945085',
    projectId: 'motobakuacademy-63832',
    databaseURL: 'https://motobakuacademy-63832-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'motobakuacademy-63832.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBhwkajbB2ZYITQEeRYLDIhP2Z_3Oo9Bg',
    appId: '1:196726945085:ios:349a945b1edc9f8fb60154',
    messagingSenderId: '196726945085',
    projectId: 'motobakuacademy-63832',
    databaseURL: 'https://motobakuacademy-63832-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'motobakuacademy-63832.appspot.com',
    iosBundleId: 'com.askerhasanov.mbauser',
  );

}